sudo: false
language: ruby
rvm:
- 2.6
install:
- gem install jekyll html-proofer jekyll-paginate jemoji
script:
- jekyll build --destination virtual-expo/
- jekyll build
- htmlproofer ./_site --disable-external
- rm -r ./virtual-expo
deploy:
  provider: pages
  skip_cleanup: true
  target_branch: gh-pages
  github_token: "$GH_TOKEN"
  on:
    branch: master